PassionProject/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PassionProject.Models
{
    public class Book
    {   
        [Key]
        public int BookId { get; set; }

        [Required, StringLength(255), Display(Name ="Book Title")]
        public string Title { get; set; }

        [StringLength(2000), Display(Name = "Book Description")]
        public string Description { get; set; }
        
        public virtual Author author { get; set; }
        public virtual Genre genre { get; set; }

    }
}

PassionProject/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PassionProject.Models;
using System.IO;
using System.Net;

namespace PassionProject.Controllers
{
    public class AuthorController : Controller
    {
        private ApplicationDBContext db = new ApplicationDBContext();
        // GET: Authors
        public ActionResult Index()
        {
            return View(db.Authors.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        [HttpPost]
        public ActionResult Edit(Author author)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        [HttpPost]
        public ActionResult New(Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

PassionProject/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PassionProject.Models;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Net;
using PassionProject.ViewModels;



namespace PassionProject.Controllers
{
    public class BookController : Controller
    {
        private ApplicationDBContext db = new ApplicationDBContext();

        public ActionResult Index()
        {
            return View(db.Books.ToList());
        }

        public ActionResult Create()
        {
            var viewmodel = new NewBookViewModel
            {
                AuthorsName = db.Authors.ToList(),
                GenreNames = db.Genres.ToList()
            };
            return View(viewmodel);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewBookViewModel newbook = new NewBookViewModel();
            newbook.Book = db.Books.Find(id);
            newbook.AuthorsName = db.Authors.ToList();
            newbook.GenreNames = db.Genres.ToList();
            if(newbook==null)
            {
                return HttpNotFound();
            }
            return View(newbook);
        }

        [HttpPost]
        public ActionResult Edit(string bookTitle,int bookId,int BookAuthor, int BookGenre,string bookDescription)
        {
            string query = "update Books set Title=@title,author_AuthorId=@author,genre_GenreId=@genre,Description=@description where BookId=" + bookId;
            SqlParameter[] myparams = new SqlParameter[4];
            myparams[0] = new SqlParameter("@title", bookTitle);
            myparams[1] = new SqlParameter("@author", BookAuthor);
            myparams[2] = new SqlParameter("@genre", BookGenre);
            myparams[3] = new SqlParameter("@description", bookDescription);
            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult New(string bookTitle, int BookAuthor,int BookGenre, string bookDescription)
        {
            string query = "insert into Books (Title,author_AuthorId,genre_GenreId,Description) values (@title,@author,@genre,@description)";
            SqlParameter[] myparams = new SqlParameter[4];
            myparams[0] = new SqlParameter("@title", bookTitle);
            myparams[1] = new SqlParameter("@author", BookAuthor);
            myparams[2] = new SqlParameter("@genre", BookGenre);
            myparams[3] = new SqlParameter("@description", bookDescription);
            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Index");
        }
    }
}

PassionProject/Controllers/GenreController.cs
using PassionProject.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PassionProject.Controllers
{
    public class GenreController : Controller
    {
        // GET: Genre
        private ApplicationDBContext db = new ApplicationDBContext();
        public ActionResult Index()
        {
            return View(db.Genres.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(Genre genre)
        {
            if (ModelState.IsValid)
            {
                db.Genres.Add(genre);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(genre);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = db.Genres.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }
        // POST: Genre/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Genre genre = db.Genres.Find(id);
            db.Genres.Remove(genre);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = db.Genres.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = db.Genres.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }
        [HttpPost]
        public ActionResult Edit(Genre genre)
        {
            if (ModelState.IsValid)
            {
                db.Entry(genre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(genre);
        }

    }
}

PassionProject/Views/Book/Create.cshtml
@model PassionProject.ViewModels.NewBookViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Add New Book</h3>


@using (Html.BeginForm("New","Book","POST")) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Book.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" id="bookTitle" name="bookTitle" class="form-control" />
            @Html.ValidationMessageFor(model => model.Book.Title, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Book.author, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select id="BookAuthor" name="BookAuthor" class="form-control">
                @foreach (var author in Model.AuthorsName)
                {
                    <option value="@author.AuthorId">@author.AuthorName</option>
                }
            </select>
            @Html.ValidationMessageFor(model => model.Book.author, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Book.genre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select id="BookGenre" name="BookGenre" class="form-control">
                @foreach (var genre in Model.GenreNames)
                {
                    <option value="@genre.GenreId">@genre.GenreName</option>
                }
            </select>
            @Html.ValidationMessageFor(model => model.Book.genre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Book.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <textarea id="bookDescription" name="bookDescription" class="form-control"></textarea>
            @Html.ValidationMessageFor(model => model.Book.Title, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    <a href="/Book"><input type='button' class='btn btn-primary' value="Back" /></a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PassionProject/Views/Book/Delete.cshtml
@model PassionProject.Models.Book

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Are you sure you want to delete <strong>@Model.Title</strong>?</h3>
<div>
    <hr />
    <table class="table table-striped">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Title)</th>
            <td>@Html.DisplayFor(model => model.Title)</td>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(model => model.author.AuthorName)</th>
            <td>@Html.DisplayFor(model => model.author.AuthorName)</td>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(model => model.genre.GenreName)</th>
            <td>@Html.DisplayFor(model => model.genre.GenreName)</td>
        </tr>
        <tr>
            <th colspan="2">
                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                    <a href="/Book"><input type='button' class='btn btn-primary' value="Back" /></a>
                </div>
            </th>
        </tr>
    </table>

    @using (Html.BeginForm("Delete","Book")) {
        @Html.AntiForgeryToken()

   
    }
</div>

PassionProject/Views/Book/Details.cshtml
@model PassionProject.Models.Book

@{
    ViewBag.Title = "Details-"+ Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>@Html.DisplayFor(model => model.Title)</h3>

<div>
    <hr />
    <table class="table table-striped">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Title)</th>
            <td>@Html.DisplayFor(model => model.Title)</td>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(model => model.author.AuthorName)</th>
            <td>@Html.DisplayFor(model => model.author.AuthorName)</td>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Description)</th>
            <td>@Html.DisplayFor(model => model.Description)</td>
        </tr>
    </table>
</div>
<p>
    <a href="/Book/Edit/@Model.BookId"><input type='button' class='btn btn-success' value="Edit" /></a>
    <a href="/Book"><input type='button' class='btn btn-primary' value="Back" /></a>
</p>

PassionProject/Views/Book/Edit.cshtml
@model PassionProject.ViewModels.NewBookViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Edit - @Model.Book.Title</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Book.BookId)

    <div class="form-group">
        @Html.LabelFor(model => model.Book.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" id="bookTitle" name="bookTitle" class="form-control" value="@Model.Book.Title" />
            <input type="hidden" id="bookId" name="bookId" class="form-control" value="@Model.Book.BookId" />
            @Html.ValidationMessageFor(model => model.Book.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Book.author.AuthorId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select id="BookAuthor" name="BookAuthor" class="form-control">
                @foreach (var author in Model.AuthorsName)
                {
                    string list = "";
                    if (author.AuthorId == Model.Book.author.AuthorId)
                    {
                        list = " selected";
                    }
                    <option value="@author.AuthorId" @list>@author.AuthorName</option>
                }
            </select>
            @Html.ValidationMessageFor(model => model.Book.author.AuthorId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Book.genre.GenreId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select id="BookGenre" name="BookGenre" class="form-control">
                @foreach (var genre in Model.GenreNames)
                {
                    string list = "";
                    if (genre.GenreId == Model.Book.genre.GenreId)
                    {
                        list = " selected";
                    }
                    <option value="@genre.GenreId" @list>@genre.GenreName</option>
                }
            </select>
            @Html.ValidationMessageFor(model => model.Book.genre.GenreId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Book.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <textarea id="bookDescription" name="bookDescription" class="form-control">@Model.Book.Description</textarea>
            @Html.ValidationMessageFor(model => model.Book.Title, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    <a href="/Book"><input type='button' class='btn btn-primary' value="Back" /></a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PassionProject/Views/Book/Index.cshtml
@model IEnumerable<PassionProject.Models.Book>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>List of books I am passionate about</h3>

<p>
    <a href="Book/Create"><input type='button' class='btn btn-primary' value="Add New Book" /></a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.author.AuthorName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.genre.GenreName)
        </th>
        <th>
            Action
        </th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.ActionLink(item.author.AuthorName, "Details/" + item.author.AuthorId, "Author")
        </td>
        <td>
            @Html.ActionLink(item.genre.GenreName, "Details/" + item.genre.GenreId, "Genre")
        </td>
            <td>
                <a href="Book/Edit/@item.BookId"><input type='button' class='btn btn-primary' value="Edit" /></a>
                <a href="Book/Details/@item.BookId"><input type='button' class='btn btn-success' value="View Details" /></a>
                <a href="Book/Delete/@item.BookId"><input type='button' class='btn btn-danger' value="Delete" /></a>
            </td>
        </tr>
        }

    </table>